name: "Lensfun"
description: "Homepage of the Lensfun library and database"

url: "http://localhost:4000"

markdown: kramdown
permalink: pretty

future: true
safe: false

exclude: [README.md]

plugins:
  - jekyll-feed

feed:
  posts_limit: 20
  categories:
    - news
    - changelogs
    - lenslist
